
function out = readdata(filepath,filename)
%
% =======================================================
% Load data from data file generated by the new labview 
% measurement suite
%
% INPUT:
% filepath:     directory containing data files
% filename:     filename of the form 'YEAR_MN_'
% run:          file number, ie run = [320 321];
%
% -------------------------------------------------------
%
% OUTPUT:
% out:       structure containing data extracted 
%               from the file
%
% =======================================================


fields = {  'Time',...
            'DCField1',...
            'DCField2',...
            'MC_Temp',...
            'Sample_Temp',...
            'Lockin1',...
            'Lockin2',...
            'Resistivity'
          };
offset = 0; %compensate is used to make the matrice's dimensions match when not all data are linked properly during the measurement.
nf = length(fields) - offset;
curdir = cd;
tot_time = 0;

tic
cd(filepath)
file = [filename '.dat'];

fid = fopen(file);
tline = importdata(file,',',4);     % The forth line contains string with a time stamp
date = char(tline(4));  %convert the cell type to string
t0 = date(7:end);    %select the date-time part of the text
t0 = datenum(t0, 'dd/mm/yyyy HH:MM:SS');
intrm = char(importdata(file,';',9));     % The ninth line contains instrument information
fclose(fid);

% mm = readtable(file,'Delimiter',{',','\t'});    %import the date from file
mm = readtable(file,'HeaderLines',14);
mm = table2array(mm(:,1:nf)); %convert the data structure to matrix
% mm = readtable(file);
% mm = table2array(mm); %convert the data structure to matrix

for n = 1:nf
    out.data.(fields{n}) = mm(:,n);   
end

% Check file for frequency scan from ZVL
if size(mm,2) > nf 
    error('More columns of data than expected!')
end

out.headers = '';
out.instrument = intrm(12:end);
out.filepath = filepath;
out.filename = file;
out.data.SerialTime = t0 + out.data.Time/86400;
out.starttime = datestr(t0);  % Time when the file was created

disp(['...loaded ' out.filename ' ' num2str(length(out.data.SerialTime)) ' data in ' num2str(toc,3) ' s'])
cd(curdir)
end

