function [fitresult, gof] = Lorentzian_fit(freq, ydata)
%CREATEFIT(freq,ydata)
%  Create a fit.
%
%  Data for 'Lorentzian' fit:
%      X Input : freq
%      Y Output: ydata
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 25-Apr-2019 20:02:18


%% Fit: 'Lorentzian'.
[xData, yData] = prepareCurveData( freq, ydata );

% Set up fittype and options.
ft = fittype( '1/pi*0.5*a/((x-b)^2+(0.5*a)^2)', 'independent', 'x', 'dependent', 'y' );
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Display = 'Off';
opts.StartPoint = [0.439167979785369 0.322609101849114];

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );

% Plot fit with data.
figure( 'Name', 'Lorentzian' );
h = plot( fitresult, xData, yData );
legend( h, 'ydata vs. freq', 'Lorentzian', 'Location', 'NorthEast' );
% Label axes
xlabel freq
ylabel ydata
grid on


