function [fitresult, gof] = Dbl_Lortz(freq11, testy, param)
%CREATEFIT(FREQ11,TESTY)
%  Create a fit.
%
%  Data for 'Dbl_Lorentz' fit:
%      X Input : freq11
%      Y Output: testy
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 24-Nov-2019 19:03:09


%% Fit: 'Dbl_Lorentz'.
[xData, yData] = prepareCurveData( freq11, testy );

% Set up fittype and options.
ft = fittype( '0.5*d1*a1/pi/((x-b1)^2+(0.5*a1)^2)+c1+0.5*d2*a2/pi/((x-b2)^2+(0.5*a2)^2)+c2', 'independent', 'x', 'dependent', 'y' );
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Display = 'Off';
opts.Lower = [-Inf -Inf -Inf -Inf -Inf -Inf -Inf -Inf];
opts.MaxFunEvals = 1000;
opts.MaxIter = 1000;
opts.StartPoint = param;
opts.Upper = [Inf Inf Inf Inf Inf Inf Inf Inf];

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );
