function [fitresult] = Lorentz_fit(freq11, testy, param)
%CREATEFIT(FREQ11,TESTY)
%  Create a fit.
%
%  Data for 'lortz_fit' fit:
%      X Input : freq11
%      Y Output: testy
%  Output:
%      fitresult : a fit object representing the fit.
%      paramc : fitted function parameter.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 23-Nov-2019 20:39:24


%% Fit: 'lortz_fit'.
[xData, yData] = prepareCurveData( freq11, testy );

% Set up fittype and options.
ft = fittype( '0.5*d*a/pi/((x-b)^2+(0.5*a)^2)+c', 'independent', 'x', 'dependent', 'y' );
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.DiffMaxChange = 0.01;
opts.Display = 'Off';
opts.Lower = [-Inf -Inf -Inf -Inf];
opts.MaxFunEvals = 1000;
opts.MaxIter = 1000;
opts.StartPoint = param;
opts.Upper = [Inf Inf Inf Inf];

% Fit model to data.
[fitresult, ~] = fit( xData, yData, ft, opts );
