
function out = readdata_v4(filepath,filename)
%
% =======================================================
% Load data from data file generated by the new labview 
% measurement suite
%
% INPUT:
% filepath:     directory containing data files
% filename:     filename of the form 'YEAR_MN_####'
%
% -------------------------------------------------------
%
% OUTPUT:
% out:       structure containing data extracted 
%               from the file
%
% =======================================================


fields = {  'Time',...
            'DCField1',...
            'DCField2',...
            'Temperature1',...
            'Temperature2',...
            'Power1',...
            'Attenuation1',...
            'lockin1',...
            'lockin2'
          };
offset = 0; %compensate is used to make the matrice's dimensions match when not all data are linked properly during the measurement.
nf = length(fields) - offset;
curdir = cd;

tic
cd(filepath)
file = [filename '.dat'];

fid = fopen(file);
tline = importdata(file,',',4);     % The forth line contains string with a time stamp
date = char(tline(4));  %convert the cell type to string
t0 = date(7:end);    %select the date-time part of the text
t0 = datenum(t0, 'dd/mm/yyyy HH:MM:SS');
fclose(fid);

mm = readtable(file,'Delimiter',{',','\t'});    %import the date from file
mm = table2array(mm); %convert the data structure to matrix

for n = 1:nf
    out.data.(fields{n}) = mm(:,n);   
end

% Check file for frequency scan from ZVL
if size(mm,2) > nf     %Counting the elements of each line to check ZVL data
    N = (size(mm,2) - nf)/3;
    out.data.ZVLfreq = mm(:,(nf+1):(nf + N));
    out.data.ZVLreal = mm(:,(nf+N+1):2:(nf + 3*N));
    out.data.ZVLimag = mm(:,(nf+N+2):2:(nf + 3*N));
end

out.headers = '';
out.instrument = '';
out.filepath = filepath;
out.filename = file;
out.data.SerialTime = t0 + out.data.Time/86400;
out.starttime = datestr(t0);  % Time when the file was created
out.nop = N;

disp(['...loaded ' out.filename ' ' num2str(length(out.data.SerialTime)) ' data in ' num2str(toc,3) ' s'])
cd(curdir)
end

